### ISSUE TITLE
Default to python3 or ask for python version, if python isn't available in shell's path

### ISSUE THREAD

**Issue by Just-Moh-it** [cake-cutter/cc#5]
On macOS, Python isn't in the path by default, or doesn't point to the latest version of python, and the `python3` command is used to execute python.

When using 
```bash
$ cc cut python main
```

The following error is generated

```bash
[|\___________] Cutting commands...Error: exec: "python": executable file not found in $PATH
```

I don't have the `python` command in the path, and though I could add it, macOS has protections in place to prevent me from doing this even if I would want to. Thus, I use python using `python3` or `python2` depending on the desired version.

I think cake-cutter should ask for the default/preferred python path of the python command if it can't find it in the shell's path, or at least give an option to customize it.

Thanks

**Comment by Dhravya** [comment]
That's a good idea, and probably can even be done by asking and then using the templating syntax.

For now, a quick fix would be to make the Cake files ask which version of python to use and then use templating to run the correct command

**Comment by kekda-py** [comment]
done. Instead of versions and stuffs. It will ask for if u are in `Mac/Linux` or `Windows` if on windows it will run
```
python -m venv env
```
or if in `Mac/Linux`
```
python3 -m venv env
```

**Comment by Just-Moh-it** [comment]
Thanks for the quick fix, your project is awesome 😃

Keep on going and keep it up!

**Comment by kekda-py** [comment]
thanks
