### ISSUE TITLE
Suggestion: Don't keep the binaries in git.

### ISSUE THREAD

**Issue by Pandademic** [cake-cutter/cc#6]
Instead , upload them when you make a release , to the "additional binaries section"

<img width="743" alt="image" src="https://user-images.githubusercontent.com/74566464/174407183-177b0459-ab3b-4adf-b08c-44c1b77434f1.png">

It's more accessible , and in general , keeping binaries in git is a bad idea.

**Comment by kekda-py** [comment]
ohhh We need to publish them to npm

**Comment by Dhravya** [comment]
Hey @Pandademic , The reason the `cc` binary is there, is so that we can directly publish to NPM.

Also, in general, git handles binary files very well, but yes, it can't handle merging of files and stuff, which we're not concerned with anyway.
